### ISSUE TITLE
GPU point buffers implicitly convert data format

### ISSUE THREAD

**Issue by nyorain** [Mortano/pasture#16]
Uploading COLOR_RGB (format `Vector3<u16>`) data to a gpu point buffer will implicitly convert the data into `Vector4<u32>`. I guess this was done to allow accessing the data from compute shaders without relying on extensions for using 8-/16-bit types and non-vec4 alignment in shaders. But for vertex data, `Vector3<u16>` is usually supported without extensions and the conversion currently leads to much wasted space. I'd also argue that this implicit conversion is unexpected (at least when using the gpu point buffers in a context besides compute shaders).

**Comment by Mortano** [comment]
Closing this since GPU-support in pasture is discontinued since version 0.4.
