### ISSUE TITLE
pasture_io - IOFactory is case sensitive

### ISSUE THREAD

**Issue by tobias93** [Mortano/pasture#9]
When using `pasture_io::base::IOFactory::default()` to construct a reader of the appropriate type for a file, it does not correctly detect the file format, if the file extension is upper case.

This is for example inconvenient, when processing files from the ahn3 data set, obtained from [here](https://downloads.pdok.nl/ahn3-downloadpage/), as the file names end in `.LAZ` instead of `.laz`, as expected by the `IOFactory`.

**Comment by Mortano** [comment]
Thanks for pointing this out. Should be easy to fix.

**Comment by Mortano** [comment]
This is fixed in `main` now and will be part of pasture `0.2.0` once it gets released.
